### ISSUE TITLE
Extension freezes the IDE with large entities 

### ISSUE THREAD

**Issue by SuliemanMansouri** [Oceanware/XAMLPowerToys#13]
### Installed product versions
- Visual Studio 2017 CE 15.6.7
- This extension: 1.5.31
- Prism.Core 6.3

### Description
Freezes the IDE when selecting large entities.
I have attached a sample that recreates the issue.

### Steps to recreate
1. Create WPF Prism blank application using prims template.
2. add a module with view and view model.
3. add class library project with large class 40+ properties.
4. reference the class in the view model as a property that uses IProportyNotification.
5. Build the Solution.
6. Start XAML power toys and select your view model and the assembly that contains the large class.
7. press next: click anywhere on the IDE it will freeze and displays (not responding).

### Current behavior
Trying to build a view from a large entity that contains 40+ properties all of them have IPropertyNotification implemented using bindable base from Prism. After selecting the view model and the library containing my entity VS IDE is grayed out and the cursor will spin indefinitely, it shows (not responding).
Opening Task manager Visual studio is just setting there doing nothing the only thing that is using memory and increases with time is PerfWatson2.exe (32bit).

### Expected behavior
It should work for large entities.

[BlankApp1.zip](https://github.com/Oceanware/XAMLPowerToys2015/files/1977493/BlankApp1.zip)

**Comment by kdawg1406** [comment]
@SuliemanMansouri  @bergerb-com apologies for VERY late response.  I'll try and look into this for you.

**Comment by SuliemanMansouri** [comment]
No worries, I will wait for the fix. for now I just reduce the number of the properties until it works then I do the rest by hand.
Still a very nice tool.
Thank you for this beautiful tool.

**Comment by kdawg1406** [comment]
I spent hours trying to upgrade this extension. I've given up. If you want to continue to use this, please make any changes you need to be successful.

**Comment by kdawg1406** [comment]
@SuliemanMansouri  just posted version for VS 2017 and VS 2019 Finally figured out how to update the product.

https://marketplace.visualstudio.com/items?itemName=KarlShifflettkdawg.XAMLPowerToysforVisualStudio2015

**Comment by kdawg1406** [comment]
@SuliemanMansouri I'm working on your too many properties issue now.  I have reproduced the issue on my monster machine.  I'll get back to you in the next day or so.

**Comment by kdawg1406** [comment]
@SuliemanMansouri I found the problem, it's an Observable Collection sort extension.  I'll rewrite this code in the morning.  Thank you for reporting this, SO SORRY I've taken WAY too LONG to respond to you.

Outstanding bug!

Best to you,

Karl

**Comment by kdawg1406** [comment]
@SuliemanMansouri next release has this fix, thank you for reporting this.  Will be live in an hour or two.

**Comment by kdawg1406** [comment]
@SuliemanMansouri you're most welcome.
