### ISSUE TITLE
Add Support For vs 2019 preview

### ISSUE THREAD

**Issue by elmondir** [Oceanware/XAMLPowerToys#15]
Add Support For vs 2019 preview

**Comment by kdawg1406** [comment]
@elmondir will do when VS 2019 is released.

**Comment by webmaster442** [comment]
Visual Studio 2019 is officially out. Can you give an information when to expect a new version which is compatible with VS 2019 ?

**Comment by kdawg1406** [comment]
I spent hours trying to upgrade this extension. I've given up. If you want to continue to use this, please make any changes you need to be successful.

**Comment by kdawg1406** [comment]
@elmondir just posted version for VS 2017 and VS 2019 Finally figured out how to update the product.  

https://marketplace.visualstudio.com/items?itemName=KarlShifflettkdawg.XAMLPowerToysforVisualStudio2015

**Comment by kdawg1406** [comment]
@elmondir you can get the build for VS 2019 here

https://marketplace.visualstudio.com/items?itemName=KarlShifflettkdawg.XAMLPowerToysforVisualStudio2015

**Comment by elmondir** [comment]
@kdawg1406 **Thank you very much**. You saved me from swinging between vs2017 and vs2019

**Comment by kdawg1406** [comment]
@elmondir I've had to remove support for VS 2017 for the moment.  I'm working with Microsoft to resolve the issue.  VS 2019 works fine.
